Branch: development
      When a user doesn't exist in the system and tries to Sign In with his/her
      LinkedIn credentials following error was thrown:

        NoMethodError (undefined method `edit_user_profile_path' for #<Users::OmniauthCallbacksController:0x00000003627610>):

      Fixed it.